repository:
  has_issues: false
  has_projects: false
  has_wiki: false
  default_branch: main
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: chore
    description: Other changes that don't modify source or test files
    color: "#fde68a"

  - name: documentation
    description: Improvements or additions to documentation
    color: "#bae6fd"

  - name: feature
    description: New feature or request
    color: "#e9d5ff"

  - name: fix
    description: Bug has been fixed
    color: "#fca5a5"

  - name: refactor
    color: "#a7f3d0"
    description: Improvements to code style

  - name: released
    color: "#e2e8f0"
    description: This code is included in a release

  - name: test
    color: "#fed7aa"
    description: Adding missing tests or correcting existing tests

teams:
  - name: Developers
    permission: maintain

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts:
          - "Verify / Build"
          - "Verify / Lint"
          - "Verify / Test"
      enforce_admins: null
      required_linear_history: null
      restrictions:
        apps: []
        users:
          - nettbureaubot
        teams: []
