name: Install
description: Installs dependencies using Yarn

runs:
  using: composite
  steps:
    # Install dependencies using Yarn without running hook scripts
    - name: Install Dependencies
      uses: bahmutov/npm-install@v1
      with:
        install-command: yarn --frozen-lockfile --ignore-scripts
