name: Annotate Pull Request

on:
  workflow_call:
    secrets:
      REPO_TOKEN:
        required: true

jobs:
  add-assignee:
    name: Add Assignee
    runs-on: warp-ubuntu-2204-x64-32x-spot
    steps:
      # Automatically add the author of the PR as the assignee
      - name: Add Assignee
        uses: toshimaru/auto-author-assign@v1.6.1
        with:
          repo-token: ${{ secrets.REPO_TOKEN }}

  apply-labels:
    name: Apply Labels
    runs-on: warp-ubuntu-2204-x64-32x-spot
    steps:
      # Automatically apply labels based on the commits
      - name: Apply Labels
        uses: fuxingloh/multi-labeler@v2.0.1
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          config-path: .github/labeler.yml
          config-repo: nettbureau/.github
