name: Build

on:
  workflow_call:
    secrets:
      ADMIN_TOKEN:
        required: true
      FONTAWESOME_AUTH_TOKEN:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: nettbureau/.github/.github/actions/install@main
        with:
          admin-token: ${{ secrets.ADMIN_TOKEN }}
          nettbureau-auth-token: ${{ secrets.GITHUB_TOKEN }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      - name: Check linting
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: nettbureau/.github/.github/actions/install@main
        with:
          admin-token: ${{ secrets.ADMIN_TOKEN }}
          nettbureau-auth-token: ${{ secrets.AUTH_TOKEN }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      - name: Check tests
        run: yarn test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: nettbureau/.github/.github/actions/install@main
        with:
          admin-token: ${{ secrets.ADMIN_TOKEN }}
          nettbureau-auth-token: ${{ secrets.AUTH_TOKEN }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      - name: Build code
        run: yarn build
