name: Build

on:
  workflow_call:
    secrets:
      FONTAWESOME_AUTH_TOKEN:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # Check out the code in the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node and install all dependencies
      - name: Install Dependencies
        uses: nettbureau/.github/.github/actions/install@main
        with:
          nettbureau-auth-token: ${{ github.token }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      # Verify that the code meets the linting requirements
      - name: Check Linting
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Check out the code in the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node and install all dependencies
      - name: Install Dependencies
        uses: nettbureau/.github/.github/actions/install@main
        with:
          nettbureau-auth-token: ${{ github.token }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      # Verify that all the tests pass
      - name: Check Tests
        run: yarn test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Check out the code in the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node and install all dependencies
      - name: Install Dependencies
        uses: nettbureau/.github/.github/actions/install@main
        with:
          nettbureau-auth-token: ${{ github.token }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      # Verify that the code builds
      - name: Build Code
        run: yarn build
