name: Build

on:
  workflow_call:
    secrets:
      FONTAWESOME_AUTH_TOKEN:
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: nettbureau/.github
          path: .github

      - uses: .github/.github/actions/setup
        with:
          nettbureau-auth-token: ${{ secrets.GITHUB_TOKEN }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      - name: Run linting
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: nettbureau/.github
          path: .github

      - uses: .github/.github/actions/setup
        with:
          nettbureau-auth-token: ${{ secrets.GITHUB_TOKEN }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      - name: Run tests
        run: yarn test --ci --coverage

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: nettbureau/.github
          path: .github

      - uses: .github/.github/actions/setup
        with:
          nettbureau-auth-token: ${{ secrets.GITHUB_TOKEN }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      - name: Build code
        run: yarn build
