name: Build

on:
  workflow_call:
    secrets:
      FONTAWESOME_AUTH_TOKEN:
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: nettbureau/.github/.github/actions/install@main
        with:
          nettbureau-auth-token: ${{ secrets.GITHUB_TOKEN }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      - name: Run linting
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: nettbureau/.github/.github/actions/install@main
        with:
          nettbureau-auth-token: ${{ secrets.AUTH_TOKEN }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      - name: Run tests
        run: yarn test --ci --coverage

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: nettbureau/.github/.github/actions/install@main
        with:
          nettbureau-auth-token: ${{ secrets.AUTH_TOKEN }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      - name: Build code
        run: yarn build
