name: Install

on:
  workflow_call:
    secrets:
      FONTAWESOME_AUTH_TOKEN:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: nettbureau/.github/.github/actions/install@main
        with:
          nettbureau-auth-token: ${{ secrets.GITHUB_TOKEN }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      - name: Fetch tags
        run: git fetch --unshallow --tags

      - name: Build code
        run: yarn build

      # Allow bypassing the GitHub branch protection
      - name: Unset header
        run: git config --local --unset http.https://github.com/.extraheader

      - name: Release packages
        run: yarn auto shipit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: nettbureaubot
          GIT_AUTHOR_EMAIL: dev@nettbureau.no
