name: Release

on:
  workflow_call:
    secrets:
      AUTH_TOKEN:
        required: true
      FONTAWESOME_AUTH_TOKEN:
        required: true
      RELEASE_TOKEN:
        required: true
      REPO_TOKEN:
        required: true
      ENV:
        required: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: 'echo -e "${{ secrets.ENV }}" >> $GITHUB_ENV'

      # Check out the code in the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node
      - name: Set Up Node
        uses: nettbureau/.github/.github/actions/setup-node@main
        with:
          nettbureau-auth-token: ${{ secrets.AUTH_TOKEN }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      # Install all dependencies
      - name: Install Dependencies
        uses: nettbureau/.github/.github/actions/install@main

      # Fetch the latest tags from Git repository
      - name: Fetch Tags
        run: git fetch --unshallow --tags

      # Allow bypassing the GitHub branch protection
      - name: Unset Header
        run: git config --local --unset http.https://github.com/.extraheader

      # Build source code for release
      - name: Build Code
        run: yarn build

      # Release packages using Auto
      - name: Release Packages
        run: yarn auto shipit --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NPM_TOKEN: ${{ github.token }}

      # Dispatch event to deploy the documentation
      - name: Deploy Documentation
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: nettbureau/docs
          event-type: deploy-wiki
