name: Install

on:
  workflow_call:
    secrets:
      READ_PACKAGES_TOKEN:
        required: true
      FONTAWESOME_AUTH_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: nettbureau/.github/.github/actions/install@main
        with:
          nettbureau-auth-token: ${{ secrets.READ_PACKAGES_TOKEN }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      - name: Fetch Git tags
        run: git fetch --unshallow --tags

      - name: Build code
        run: yarn build

      - name: Test npmrc
        run: npm config list

      - name: Test npm login
        run: npm login --scope=@nettbureau --registry=https://npm.pkg.github.com

      - name: Test env
        run: yarn exec -- node -e "console.log(process.env)"

      - name: Release
        run: yarn auto shipit
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}
