name: Install

on:
  workflow_call:
    secrets:
      FONTAWESOME_AUTH_TOKEN:
        required: true
      RELEASE_TOKEN:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # Check out the code in the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node and install all dependencies
      - name: Install dependencies
        uses: nettbureau/.github/.github/actions/install@main
        with:
          nettbureau-auth-token: ${{ github.token }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      # Fetch the latest tags from Git repository
      - name: Fetch tags
        run: git fetch --unshallow --tags

      # Allow bypassing the GitHub branch protection
      - name: Unset header
        run: git config --local --unset http.https://github.com/.extraheader

      # Build source code for release
      - name: Build code
        run: yarn build

      # Release packages using Auto
      - name: Release packages
        run: yarn auto shipit
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
