name: Install

on:
  workflow_call:
    secrets:
      NETTBUREAU_AUTH_TOKEN:
        required: true
      FONTAWESOME_AUTH_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: nettbureau/.github/.github/actions/install@main
        with:
          nettbureau-auth-token: ${{ secrets.NETTBUREAU_AUTH_TOKEN }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      - name: Fetch Git tags
        run: git fetch --unshallow --tags

      - name: Build code
        run: yarn build

      - name: Release
        run: yarn auto shipit
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
