name: Install

on:
  workflow_call:
    secrets:
      AUTH_TOKEN:
        required: true
      FONTAWESOME_AUTH_TOKEN:
        required: true
      RELEASE_TOKEN:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # Set up Node and install all dependencies
      - name: Install Dependencies
        uses: nettbureau/.github/.github/actions/install@main
        with:
          nettbureau-auth-token: ${{ secrets.AUTH_TOKEN }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      # Fetch the latest tags from Git repository
      - name: Fetch Tags
        run: git fetch --unshallow --tags

      # Allow bypassing the GitHub branch protection
      - name: Unset Header
        run: git config --local --unset http.https://github.com/.extraheader

      # Build source code for release
      - name: Build Code
        run: yarn build

      # Release packages using Auto
      - name: Release Packages
        run: yarn auto shipit --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NPM_TOKEN: ${{ github.token }}
