name: Install

on:
  workflow_call:
    secrets:
      FONTAWESOME_AUTH_TOKEN:
        required: true
      RELEASE_TOKEN:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # Set up Node and install all dependencies
      - name: Install Dependencies
        uses: nettbureau/.github/.github/actions/install@main
        with:
          nettbureau-auth-token: ${{ github.token }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      # Install Lerna which Auto uses to resolve monorepo packages
      - name: Install Lerna
        run: yarn add lerna -DW

      # Create a Lerna configuration file
      - name: Configure Lerna
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "lerna.json"
          json: '{"npmClient": "yarn", "useWorkspaces": true}'

      # Create a Lerna configuration file
      - name: Debug Lerna
        run: ls -la

      # Fetch the latest tags from Git repository
      - name: Fetch Tags
        run: git fetch --unshallow --tags

      # Allow bypassing the GitHub branch protection
      - name: Unset Header
        run: git config --local --unset http.https://github.com/.extraheader

      # Build source code for release
      - name: Build Code
        run: yarn build

      # Release packages using Auto
      - name: Release Packages
        run: yarn auto shipit
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NPM_TOKEN: ${{ github.token }}
