name: Report Size

on:
  workflow_call:
    inputs:
      pattern:
        type: string
        default: "./{apps,packages}/*/dist/*.{js,css}"
    secrets:
      REPORT_TOKEN:
        required: true

jobs:
  report-size:
    name: Report Size
    runs-on: ubuntu-latest
    steps:
      # Check out the code in the repository
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPORT_TOKEN }}

      - name: Report Size
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: ${{ inputs.pattern }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPORT_TOKEN }}
          GIT_AUTHOR_NAME: nettbureaubot
          GIT_AUTHOR_EMAIL: dev@nettbureau.no
          GIT_COMMITTER_NAME: nettbureaubot
          GIT_COMMITTER_EMAIL: dev@nettbureau.no
