name: Report Size

on:
  workflow_call:
    inputs:
      pattern:
        type: string
        default: "./{apps,packages}/*/dist/*.{js,css}"
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  report-size:
    name: Report Size
    runs-on: ubuntu-latest
    steps:
      # Check out the code in the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Report Size
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: ${{ inputs.pattern }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
