name: Report Size

on:
  workflow_call:
    inputs:
      pattern:
        type: string
        default: "./{apps,packages}/*/dist/*.{js,css}"

jobs:
  report-size:
    name: Report size
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Report size
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: ${{ inputs.pattern }}
        env:
          GIT_AUTHOR_NAME: nettbureaubot
          GIT_AUTHOR_EMAIL: dev@nettbureau.no
