name: Report Size

on:
  workflow_call:
    inputs:
      pattern:
        required: false
        type: string
        default: "./{apps,packages}/*/dist/*.{js,css}"
    secrets:
      AUTH_TOKEN:
        required: true
      FONTAWESOME_AUTH_TOKEN:
        required: true
      REPO_TOKEN:
        required: true
      ENV:
        required: false

jobs:
  report-size:
    name: Report Size
    runs-on: warp-ubuntu-latest-arm64-4x-spot
    # To use Turborepo Remote Caching, set the following environment variables for the job.
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: "nettbureau"
    steps:
      - name: Set Environment Variables
        run: 'echo -e "${{ secrets.ENV }}" >> $GITHUB_ENV'

      # Check out the code in the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node
      - name: Set Up Node
        uses: nettbureau/.github/.github/actions/setup-node@main
        with:
          nettbureau-auth-token: ${{ secrets.AUTH_TOKEN }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      # Comment on the pull request with a report of the size of the files
      - name: Report Size
        uses: preactjs/compressed-size-action@master
        with:
          pattern: ${{ inputs.pattern }}
          exclude: "{**/*.map,**/node_modules/**}"
          repo-token: ${{ secrets.REPO_TOKEN }}
        env:
          SKIP_ZOD_PRISMA: true
          SKIP_ENV_VALIDATION: true
