name: Report Size

on:
  workflow_call:
    inputs:
      pattern:
        type: string
        default: "./{apps,packages}/*/dist/*.{js,css}"
    secrets:
      REPO_TOKEN:
        required: true

jobs:
  report-size:
    name: Report Size
    runs-on: ubuntu-latest
    steps:
      # Check out the code in the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Comment on the pull request with a report of the size of the files
      - name: Report Size
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: ${{ inputs.pattern }}
          repo-token: ${{ secrets.REPO_TOKEN }}
