name: Build

on:
  workflow_call:
    secrets:
      AUTH_TOKEN:
        required: true
      FONTAWESOME_AUTH_TOKEN:
        required: true
      ENV:
        required: false

jobs:
  verify:
    name: Verify
    runs-on: warp-ubuntu-2204-x64-32x-spot
    # To use Turborepo Remote Caching, set the following environment variables for the job.
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: "nettbureau"
    steps:
      - name: Set Environment Variables
        run: 'echo -e "${{ secrets.ENV }}" >> $GITHUB_ENV'

      # Check out the code in the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node
      - name: Set Up Node
        uses: nettbureau/.github/.github/actions/setup-node@main
        with:
          nettbureau-auth-token: ${{ secrets.AUTH_TOKEN }}
          fontawesome-auth-token: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}

      # Install all dependencies
      - name: Install Dependencies
        uses: nettbureau/.github/.github/actions/install@main

      # Verify that the code builds
      - name: Build Code
        run: yarn build

      # Verify that the code meets the linting requirements
      - name: Check Linting
        run: yarn lint

      # Verify that all the tests pass
      - name: Check Tests
        run: yarn test
